#!/bin/bash

die() {
        echo "#####"
        echo $1
        echo "#####"
        exit 1
}

if [ $1 = "install" ]; then
	chmod 0700 ${MY_INSTALLDIR}/zp-data || die

elif [ $1 = "clean" ]; then
	echo $1
fi

